### ISSUE TITLE
[please add] Cooking for Blockheads

### ISSUE THREAD

**Issue by iamweirdie** [kreezxil/Hell-on-Earth#1]
Mod Link: [https://minecraft.curseforge.com/projects/cooking-for-blockheads](https://minecraft.curseforge.com/projects/cooking-for-blockheads)

The beginning of the Primal core mod has a fair amount of inventory management, but there's so much food from Pam's mods that they just overflow the inventory. Sure you can spam storage, add in mods like Colossal chests, but iron is a valued resource on here that the player might avoid it. With this mod, you have more storage options but at the same time, you have a recipe book/block that shows you what food items you can craft based on what you have. This greatly benefits any players of Pam's mods, as the mods tend to add in lots of micro-crops that combine to make bigger recipes.

**Comment by kreezxil** [comment]
excellent dissertation, consider it added.
